//! Comment delimiters and file extensions.
//!
//! Generated from `leo/leolib/language_data.py` and `leo/leolib/state.py`, which
//! is why the entries are neither grouped nor commented: they must stay a copy
//! of Leo's tables, not a curated subset. The readers need to know that a `.py`
//! file is Python with no application running.

use once_cell::sync::Lazy;
use std::collections::HashMap;

/// File extension (no period) -> language name.
static EXTENSION_DICT_DATA: &[(&str, &str)] = &[
    ("ADA", "ada95"),
    ("BAS", "rapidq"),
    ("BAT", "batch"),
    ("C", "cplusplus"),
    ("CBL", "cobol"),
    ("CC", "cplusplus"),
    ("CMD", "batch"),
    ("CPP", "cplusplus"),
    ("F", "fortran"),
    ("F90", "fortran90"),
    ("H", "c"),
    ("IDL", "idl"),
    ("INI", "ini"),
    ("JSON", "json"),
    ("MAK", "makefile"),
    ("MD", "md"),
    ("MOD", "modula3"),
    ("P", "pascal"),
    ("PL", "perl"),
    ("PL1", "pl1"),
    ("PRG", "foxpro"),
    ("PRO", "prolog"),
    ("PS", "postscript"),
    ("RB", "ruby"),
    ("REX", "objectrexx"),
    ("SH", "shell"),
    ("SQL", "plsql"),
    ("TCL", "tcl"),
    ("TEX", "latex"),
    ("TXT", "plain"),
    ("VHD", "vhdl"),
    ("VHDL", "vhdl"),
    ("VIM", "vim"),
    ("YAML", "yaml"),
    ("ada", "ada95"),
    ("ahk", "autohotkey"),
    ("aj", "aspect_j"),
    ("apdl", "apdl"),
    ("as", "actionscript"),
    ("asp", "asp"),
    ("awk", "awk"),
    ("b", "b"),
    ("bas", "rapidq"),
    ("bash", "shellscript"),
    ("bat", "batch"),
    ("bbj", "bbj"),
    ("bcel", "bcel"),
    ("bib", "bibtex"),
    ("c", "c"),
    ("c++", "cplusplus"),
    ("cbl", "cobol"),
    ("cc", "cplusplus"),
    ("cfg", "config"),
    ("cfm", "coldfusion"),
    ("ch", "chill"),
    ("clj", "clojure"),
    ("cljc", "clojure"),
    ("cljs", "clojure"),
    ("cmd", "batch"),
    ("cob", "cobol"),
    ("codon", "codon"),
    ("coffee", "coffeescript"),
    ("comp", "glsl"),
    ("conf", "apacheconf"),
    ("cpp", "cplusplus"),
    ("css", "css"),
    ("d", "d"),
    ("dart", "dart"),
    ("e", "eiffel"),
    ("el", "elisp"),
    ("eml", "mail"),
    ("erl", "erlang"),
    ("ex", "elixir"),
    ("f", "fortran"),
    ("f90", "fortran90"),
    ("factor", "factor"),
    ("forth", "forth"),
    ("frag", "glsl"),
    ("g", "antlr"),
    ("geom", "glsl"),
    ("glsl", "glsl"),
    ("go", "go"),
    ("groovy", "groovy"),
    ("h", "c"),
    ("handlebars", "html"),
    ("hbs", "html"),
    ("hh", "cplusplus"),
    ("hs", "haskell"),
    ("html", "html"),
    ("hx", "haxe"),
    ("i", "swig"),
    ("i4gl", "i4gl"),
    ("icn", "icon"),
    ("idl", "idl"),
    ("inf", "inform"),
    ("info", "texinfo"),
    ("ini", "ini"),
    ("io", "io"),
    ("ipynb", "jupytext"),
    ("iss", "inno_setup"),
    ("jade", "pug"),
    ("java", "java"),
    ("jhtml", "jhtml"),
    ("jl", "julia"),
    ("jmk", "jmk"),
    ("js", "javascript"),
    ("json", "json"),
    ("jsp", "javaserverpage"),
    ("ksh", "kshell"),
    ("kv", "kivy"),
    ("latex", "latex"),
    ("less", "css"),
    ("lua", "lua"),
    ("ly", "lilypond"),
    ("m", "matlab"),
    ("mak", "makefile"),
    ("md", "md"),
    ("ml", "ml"),
    ("mm", "objective_c"),
    ("mod", "modula3"),
    ("mpl", "maple"),
    ("mqsc", "mqsc"),
    ("nim", "nim"),
    ("nqc", "nqc"),
    ("nsi", "nsi"),
    ("nw", "noweb"),
    ("occ", "occam"),
    ("otl", "vimoutline"),
    ("p", "pascal"),
    ("php", "php"),
    ("pike", "pike"),
    ("pl", "perl"),
    ("pl1", "pl1"),
    ("po", "gettext"),
    ("pod", "perlpod"),
    ("pov", "povray"),
    ("prg", "foxpro"),
    ("pro", "prolog"),
    ("ps", "postscript"),
    ("psp", "psp"),
    ("ptl", "ptl"),
    ("pug", "pug"),
    ("py", "python"),
    ("pyx", "cython"),
    ("r", "rebol"),
    ("rb", "ruby"),
    ("rest", "rst"),
    ("rex", "objectrexx"),
    ("rhtml", "rhtml"),
    ("rib", "rib"),
    ("rs", "rust"),
    ("sas", "sas"),
    ("scad", "openscad"),
    ("scala", "scala"),
    ("scm", "scheme"),
    ("scpt", "applescript"),
    ("sgml", "sgml"),
    ("sh", "shell"),
    ("shtml", "shtml"),
    ("sm", "smalltalk"),
    ("splus", "splus"),
    ("sql", "plsql"),
    ("sqr", "sqr"),
    ("ss", "ssharp"),
    ("ssi", "shtml"),
    ("sty", "latex"),
    ("tcl", "tcl"),
    ("tesc", "glsl"),
    ("tese", "glsl"),
    ("tex", "latex"),
    ("toml", "toml"),
    ("tpl", "tpl"),
    ("ts", "typescript"),
    ("txt", "plain"),
    ("typ", "typst"),
    ("typst", "typst"),
    ("uc", "uscript"),
    ("v", "verilog"),
    ("vbs", "vbscript"),
    ("vert", "glsl"),
    ("vhd", "vhdl"),
    ("vhdl", "vhdl"),
    ("vim", "vim"),
    ("vtl", "velocity"),
    ("vue", "javascript"),
    ("w", "cweb"),
    ("wiki", "moin"),
    ("xml", "xml"),
    ("xom", "omnimark"),
    ("xsl", "xsl"),
    ("yaml", "yaml"),
    ("zpt", "zpt"),
];

pub fn extension_dict() -> &'static HashMap<&'static str, &'static str> {
    static M: Lazy<HashMap<&'static str, &'static str>> =
        Lazy::new(|| EXTENSION_DICT_DATA.iter().copied().collect());
    &M
}

/// Language name -> the delimiters an @comment directive would name.
static LANGUAGE_DELIMS_DICT_DATA: &[(&str, &str)] = &[
    ("actionscript", "// /* */"),
    ("ada", "--"),
    ("ada95", "--"),
    ("ahk", ";"),
    ("antlr", "// /* */"),
    ("apacheconf", "#"),
    ("apdl", "!"),
    ("applescript", "-- (* *)"),
    ("asp", "<!-- -->"),
    ("aspect_j", "// /* */"),
    ("assembly_6502", ";"),
    ("assembly_macro32", ";"),
    ("assembly_mcs51", ";"),
    ("assembly_parrot", "#"),
    ("assembly_r2000", "#"),
    ("assembly_x86", ";"),
    ("autohotkey", "; /* */"),
    ("awk", "#"),
    ("b", "// /* */"),
    ("batch", "REM_"),
    ("bbj", "/* */"),
    ("bcel", "// /* */"),
    ("bibtex", "%"),
    ("c", "// /* */"),
    ("chill", "/* */"),
    ("clojure", ";"),
    ("cobol", "*"),
    ("codon", "#"),
    ("coffeescript", "#"),
    ("coldfusion", "<!-- -->"),
    ("config", "#"),
    ("cplusplus", "// /* */"),
    ("cpp", "// /* */"),
    ("csharp", "// /* */"),
    ("css", "/* */"),
    ("cweb", "@q@ @>"),
    ("cython", "#"),
    ("d", "// /* */"),
    ("dart", "// /* */"),
    ("doxygen", "#"),
    ("eiffel", "--"),
    ("elisp", ";"),
    ("elixir", "#"),
    ("erlang", "%"),
    ("factor", "!_ ( )"),
    ("forth", "\\_ _(_ _)"),
    ("fortran", "C"),
    ("fortran90", "!"),
    ("foxpro", "&&"),
    ("gettext", "# "),
    ("glsl", "// /* */"),
    ("go", "//"),
    ("groovy", "// /* */"),
    ("handlebars", "<!-- -->"),
    ("haskell", "--_ {-_ _-}"),
    ("haxe", "// /* */"),
    ("hbs", "<!-- -->"),
    ("html", "<!-- -->"),
    ("i4gl", "-- { }"),
    ("icon", "#"),
    ("idl", "// /* */"),
    ("inform", "!"),
    ("ini", ";"),
    ("inno_setup", ";"),
    ("interlis", "/* */"),
    ("io", "// */"),
    ("java", "// /* */"),
    ("javascript", "// /* */"),
    ("javaserverpage", "<%-- --%>"),
    ("jhtml", "<!-- -->"),
    ("jmk", "#"),
    ("json", "#"),
    ("jsp", "<%-- --%>"),
    ("julia", "#"),
    ("jupyter", "<%-- --%>"),
    ("jupytext", "#"),
    ("katex", "%"),
    ("kivy", "#"),
    ("kshell", "#"),
    ("latex", "%"),
    ("less", "/* */"),
    ("lilypond", "% %{ %}"),
    ("lisp", ";"),
    ("lotos", "(* *)"),
    ("lua", "--"),
    ("mail", ">"),
    ("makefile", "#"),
    ("maple", "//"),
    ("markdown", "<!-- -->"),
    ("mathjax", "% <!-- -->"),
    ("matlab", "%"),
    ("md", "<!-- -->"),
    ("ml", "(* *)"),
    ("modula3", "(* *)"),
    ("moin", "##"),
    ("mqsc", "*"),
    ("netrexx", "-- /* */"),
    ("nim", "#"),
    ("noweb", "%"),
    ("nqc", "// /* */"),
    ("nsi", ";"),
    ("nsis2", ";"),
    ("objective_c", "// /* */"),
    ("objectrexx", "-- /* */"),
    ("ocaml", "(* *)"),
    ("occam", "--"),
    ("omnimark", ";"),
    ("openscad", "// /* */"),
    ("pandoc", "<!-- -->"),
    ("pascal", "// { }"),
    ("perl", "#"),
    ("perlpod", "# __=pod__ __=cut__"),
    ("php", "// /* */"),
    ("pike", "// /* */"),
    ("pl1", "/* */"),
    ("plain", "#"),
    ("plsql", "-- /* */"),
    ("pop11", ";;; /* */"),
    ("postscript", "%"),
    ("povray", "// /* */"),
    ("powerdynamo", "// <!-- -->"),
    ("prolog", "% /* */"),
    ("psp", "<!-- -->"),
    ("ptl", "#"),
    ("pug", "//-"),
    ("pvwave", ";"),
    ("pyrex", "#"),
    ("python", "#"),
    ("r", "#"),
    ("rapidq", "'"),
    ("rebol", ";"),
    ("redcode", ";"),
    ("rest", ".._"),
    ("rhtml", "<%# %>"),
    ("rib", "#"),
    ("rpmspec", "#"),
    ("rst", ".._"),
    ("ruby", "#"),
    ("rust", "// /* */"),
    ("rview", "// /* */"),
    ("sas", "* /* */"),
    ("scala", "// /* */"),
    ("scheme", "; #| |#"),
    ("sdl_pr", "/* */"),
    ("sgml", "<!-- -->"),
    ("shell", "#"),
    ("shellscript", "#"),
    ("shtml", "<!-- -->"),
    ("smalltalk", "\" \""),
    ("smi_mib", "--"),
    ("splus", "#"),
    ("sqr", "!"),
    ("squidconf", "#"),
    ("ssharp", "#"),
    ("swig", "// /* */"),
    ("tcl", "#"),
    ("tcltk", "#"),
    ("tex", "%"),
    ("texinfo", "@c"),
    ("text", "#"),
    ("toml", "#"),
    ("tpl", "<!-- -->"),
    ("tsql", "-- /* */"),
    ("typescript", "// /* */"),
    ("typst", "//"),
    ("unknown", "#"),
    ("unknown_language", "#--unknown-language--"),
    ("uscript", "// /* */"),
    ("vbscript", "'"),
    ("velocity", "## #* *#"),
    ("verilog", "// /* */"),
    ("vhdl", "--"),
    ("vim", "\""),
    ("vimoutline", "#"),
    ("xml", "<!-- -->"),
    ("xsl", "<!-- -->"),
    ("xslt", "<!-- -->"),
    ("yaml", "#"),
    ("zpt", "<!-- -->"),
];

pub fn language_delims_dict() -> &'static HashMap<&'static str, &'static str> {
    static M: Lazy<HashMap<&'static str, &'static str>> =
        Lazy::new(|| LANGUAGE_DELIMS_DICT_DATA.iter().copied().collect());
    &M
}

/// Language name -> its canonical file extension.
static LANGUAGE_EXTENSION_DICT_DATA: &[(&str, &str)] = &[
    ("actionscript", "as"),
    ("ada", "ada"),
    ("ada95", "ada"),
    ("ahk", "ahk"),
    ("antlr", "g"),
    ("apacheconf", "conf"),
    ("apdl", "apdl"),
    ("applescript", "scpt"),
    ("asp", "asp"),
    ("aspect_j", "aj"),
    ("autohotkey", "ahk"),
    ("awk", "awk"),
    ("b", "b"),
    ("batch", "bat"),
    ("bbj", "bbj"),
    ("bcel", "bcel"),
    ("bibtex", "bib"),
    ("c", "c"),
    ("chill", "ch"),
    ("clojure", "clj"),
    ("cobol", "cbl"),
    ("codon", "codon"),
    ("coffeescript", "coffee"),
    ("coldfusion", "cfm"),
    ("config", "cfg"),
    ("cplusplus", "c++"),
    ("cpp", "cpp"),
    ("css", "css"),
    ("cweb", "w"),
    ("cython", "pyx"),
    ("d", "d"),
    ("dart", "dart"),
    ("eiffel", "e"),
    ("elisp", "el"),
    ("elixir", "ex"),
    ("erlang", "erl"),
    ("factor", "factor"),
    ("forth", "forth"),
    ("fortran", "f"),
    ("fortran90", "f90"),
    ("foxpro", "prg"),
    ("gettext", "po"),
    ("glsl", "glsl"),
    ("go", "go"),
    ("groovy", "groovy"),
    ("haskell", "hs"),
    ("haxe", "hx"),
    ("html", "html"),
    ("i4gl", "i4gl"),
    ("icon", "icn"),
    ("idl", "idl"),
    ("inform", "inf"),
    ("ini", "ini"),
    ("inno_setup", "iss"),
    ("io", "io"),
    ("java", "java"),
    ("javascript", "js"),
    ("javaserverpage", "jsp"),
    ("jhtml", "jhtml"),
    ("jmk", "jmk"),
    ("json", "json"),
    ("jsp", "jsp"),
    ("julia", "jl"),
    ("jupytext", "ipynb"),
    ("kivy", "kv"),
    ("kshell", "ksh"),
    ("latex", "tex"),
    ("lilypond", "ly"),
    ("lua", "lua"),
    ("mail", "eml"),
    ("makefile", "mak"),
    ("maple", "mpl"),
    ("matlab", "m"),
    ("md", "md"),
    ("ml", "ml"),
    ("modula3", "mod"),
    ("moin", "wiki"),
    ("mqsc", "mqsc"),
    ("nim", "nim"),
    ("noweb", "nw"),
    ("nqc", "nqc"),
    ("nsi", "nsi"),
    ("nsis2", "nsi"),
    ("objective_c", "mm"),
    ("objectrexx", "rex"),
    ("ocaml", "ml"),
    ("occam", "occ"),
    ("omnimark", "xom"),
    ("openscad", "scad"),
    ("pascal", "p"),
    ("perl", "pl"),
    ("perlpod", "pod"),
    ("php", "php"),
    ("pike", "pike"),
    ("pl1", "pl1"),
    ("plain", "txt"),
    ("plsql", "sql"),
    ("postscript", "ps"),
    ("povray", "pov"),
    ("prolog", "pro"),
    ("psp", "psp"),
    ("ptl", "ptl"),
    ("pug", "pug"),
    ("pyrex", "pyx"),
    ("python", "py"),
    ("r", "r"),
    ("rapidq", "bas"),
    ("rebol", "r"),
    ("rhtml", "rhtml"),
    ("rib", "rib"),
    ("rst", "rest"),
    ("ruby", "rb"),
    ("rust", "rs"),
    ("sas", "sas"),
    ("scala", "scala"),
    ("scheme", "scm"),
    ("sgml", "sgml"),
    ("shell", "sh"),
    ("shellscript", "bash"),
    ("shtml", "ssi"),
    ("smalltalk", "sm"),
    ("splus", "splus"),
    ("sqr", "sqr"),
    ("ssharp", "ss"),
    ("swig", "i"),
    ("tcl", "tcl"),
    ("tcltk", "tcl"),
    ("tex", "tex"),
    ("texinfo", "info"),
    ("text", "txt"),
    ("toml", "toml"),
    ("tpl", "tpl"),
    ("tsql", "sql"),
    ("typescript", "ts"),
    ("typst", "typ"),
    ("unknown", "txt"),
    ("uscript", "uc"),
    ("vbscript", "vbs"),
    ("velocity", "vtl"),
    ("verilog", "v"),
    ("vhdl", "vhd"),
    ("vim", "vim"),
    ("vimoutline", "otl"),
    ("xml", "xml"),
    ("xsl", "xsl"),
    ("xslt", "xsl"),
    ("yaml", "yaml"),
    ("zpt", "zpt"),
];

pub fn language_extension_dict() -> &'static HashMap<&'static str, &'static str> {
    static M: Lazy<HashMap<&'static str, &'static str>> =
        Lazy::new(|| LANGUAGE_EXTENSION_DICT_DATA.iter().copied().collect());
    &M
}

/// Extensions Leo knows but does not colour.
static EXTRA_EXTENSION_DICT_DATA: &[(&str, &str)] =
    &[("pod", "perl"), ("unknown_language", "none"), ("w", "c")];

pub fn extra_extension_dict() -> &'static HashMap<&'static str, &'static str> {
    static M: Lazy<HashMap<&'static str, &'static str>> =
        Lazy::new(|| EXTRA_EXTENSION_DICT_DATA.iter().copied().collect());
    &M
}

/// Languages coloured by another language's rules.
static DELEGATE_LANGUAGE_DICT_DATA: &[(&str, &str)] = &[
    ("codon", "python"),
    ("elisp", "lisp"),
    ("glsl", "c"),
    ("handlebars", "html"),
    ("hbs", "html"),
    ("katex", "html"),
    ("less", "css"),
    ("mathjax", "html"),
    ("toml", "ini"),
];

pub fn delegate_language_dict() -> &'static HashMap<&'static str, &'static str> {
    static M: Lazy<HashMap<&'static str, &'static str>> =
        Lazy::new(|| DELEGATE_LANGUAGE_DICT_DATA.iter().copied().collect());
    &M
}
