<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: https://leo-editor.github.io/leo-editor/leo_toc.html -->
<leo_file xmlns:leo="https://leo-editor.github.io/leo-editor/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="sta.20260909214154.2"><vh>demo</vh>
<v t="sta.20260909214201.1"><vh>@auto okr.py</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="sta.20260909214154.2">@language python
</t>
</tnodes>
</leo_file>
